# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-20 04:42
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Boutique',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shop_name', models.CharField(max_length=500)),
                ('user', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=250)),
                ('product_img', models.FileField(upload_to='')),
                ('product_price', models.FloatField(max_length=100)),
                ('product_desc', models.CharField(max_length=500)),
                ('boutique', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='boutique.Boutique')),
            ],
        ),
    ]
