# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-21 11:56
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('boutique', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='boutique',
            old_name='boutique_name',
            new_name='shop_name',
        ),
    ]
